name: bushu-bot

on:
  schedule:
    - cron: '45 18 * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: 运行脚本
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py

      - name: 上传截图
        uses: actions/upload-artifact@v4
        with:
          name: result
          path
